packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  argon2: false
  msgpackr-extract: false
  prisma: false
  sharp: false
  unrs-resolver: false
